return {
  -- lazy.nvim
  -- {
  --   "folke/snacks.nvim",
  --   ---@type snacks.Config
  --   opts = {
  --     image = {},
  --   },
  -- },
  -- {
  --   "chipsenkbeil/org-roam.nvim",
  --   -- tag = "0.1.1",
  --   dependencies = {
  --     {
  --       "nvim-orgmode/orgmode",
  --       -- tag = "0.3.7",
  --       dependencies = {
  --         "nvim-orgmode/org-bullets.nvim",
  --         "danilshvalov/org-modern.nvim",
  --       },
  --       event = "VeryLazy",
  --       ft = { "org" },
  --       opts = {
  --         org_agenda_files = "~/Org/**",
  --         org_default_notes_file = "~/Org/refile.org",
  --         mappings = {
  --           prefix = "<Localleader>o",
  --         },
  --         ui = {
  --           menu = {
  --             handler = function(data)
  --               require("org-modern.menu")
  --                 :new({
  --                   window = {
  --                     margin = { 1, 0, 1, 0 },
  --                     padding = { 0, 1, 0, 1 },
  --                     title_pos = "center",
  --                     border = "single",
  --                     zindex = 1000,
  --                   },
  --                   icons = {
  --                     separator = "",
  --                   },
  --                 })
  --                 :open(data)
  --             end,
  --           },
  --         },
  --       },
  --     },
  --   },
  --   event = "VeryLazy",
  --   ft = { "org" },
  --   opts = {
  --     directory = "~/Org/notes",
  --     org_files = {
  --       "~/Org/refile.org",
  --     },
  --     bindings = {
  --       prefix = "<Localleader>n",
  --     },
  --   },
  -- },
}
